package com.Q6_Constructor_Throws_Exception;

public class Parent {

	
		Parent() throws Exception{
			
			System.out.println("Inside parent constructor");
		}
	
		public void fun1(){
			
			System.out.println("inside fun1 of Parent class");
		}

	
}
